# Site
repository: ml_web
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Huanhuan Chen (Milian)
# title: Your job title
email: miliuumeru@gmail.com
# email_title: Email (Email title override)
phone: (86) 193-0213-7201
# phone_title: Phone (Phone title override)
website: https://https://miliuumeru.github.io/ml_web
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  miliuumeru
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: red_milian
linkedin_username: huanhuan chen
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Avatar.png
about_content: |
  Half artist, half coder, obsessed with making something fun, impressive, and alive.

  Skills:
    - Game Engines: Unreal, Unity, Snowdrop (Ubisoft)
    - 3D DCC: Maya, 3ds Max
    - 2D DCC: Clip Studio Paint, Photoshop
    - Programming: Python (advanced), Qt (working knowledge), Maya API (working knowledge), C++ (basic familiarity)

content:
  # - title: Projects
  #   layout: list
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Personal Animation <SEED>
  #       # link: https://youtu.be/9jc6oblx0aY
  #       # link_text: Watch it on YouTube
  #       additional_links:
  #         - title:  YouTube page for project
  #           icon: fab fa-youtube
  #           url: https://youtu.be/9jc6oblx0aY
  #         - title:  Vimeo page for project
  #           icon: fab fa-vimeo
  #           url: https://vimeo.com/1137545512
  #       quote: |
  #         ww
  #       description: | # this will include new lines to allow paragraphs
  #         Created with Maya and RenderMan. All visuals were crafted by me, and the music was composed by a friend.
  - title: Personal Animation <SEED>
    layout: text
    content: |
      ![](images/SEED_Poster.jpg)

      Watch this 6-minute video on [**YouTube**](https://youtu.be/9jc6oblx0aY) or [**Vimeo**](https://vimeo.com/1137545512)


      This personal animation is created with Maya and RenderMan. All visuals were crafted by me, and the music was composed by a friend.


      **2D sketches**

      At first I set out to tell a story about a creature that feels familiar yet subtly unusual—someone who longs to fly. 
      Then I identified the protagonist: an ant, arguably the least likely creature to  reach the sky.
      I set up a backdrop with blue-tree forest, the protagonist’s walnut house, and a snapshot of his daily life within this imagined world.

      ![](images/SEED_4.jpg)
      ![](images/SEED_5.jpg)
      ![](images/SEED_6.jpg)


      **3D modelling and rigging**

      The next phase is asset producing, the characters, props, and scenes, and driving them into full rigging.

      ![](images/SEED_7.jpg)
      ![](images/SEED_8.jpg)
      ![](images/SEED_9.jpg)


      **Animation and compositing**

      This phase focuses on animation, simulation, and compositing.

      ![](images/SEED_10.gif)
      ![](images/SEED_11.gif)
      ![](images/SEED_12.gif)


      **Final work clips**

      ![](images/SEED_1.gif)
      ![](images/SEED_2.gif)
      ![](images/SEED_3.gif)
  - title: Scripts
    layout: text
    content: |
      ![](images/Pet_Poster.jpg)

      Source code on [**GitHub**](https://github.com/miliuumeru/ml_desktop_pet)


      I’m a fan of pixel art, so I built a desktop pet based on my avatar to keep me company.

      This is fully Python-based with no external game engine. 
      

      **Pet behaviours**

      ![](images/Pet.gif)


      **Main code and animation state machine part**

      I built designated UI, animation system, and configuration framework for it, allowing users to customize sleep time, meal time, and birthday greetings (which makes pet real).

      ![](images/Pet_Script.jpg)


      ![](images/Hair_Poster.jpg)

      Source code on [**GitHub**](https://github.com/miliuumeru/ml_hair_rigging)

      An auto hair-binding rigging tool for Maya.
      The workflow breaks down into four core steps:
      1. Convert the hair’s poly meshes into curves (the curves must be generated along the mesh’s central axis rather than on its surface.);
      2. Rebuild those curves and generate joints along them;
      3. Implement a kinetic hair physics system;
      4. Skin the meshes to the joint chains.

      ![](images/YJ_2.gif)
      ![](images/Hair_Script.jpg)
  - title: Modeling & Rendering
    layout: text
    content: |
      ![](images/Render_Poster.jpg)

      ![](images/Render_1.gif)
      ![](images/Render_2.jpg)
      ![](images/Render_3.jpg)
      ![](images/Render_4.jpg)
  - title: 3D Printing
    layout: text
    content: |
      ![](images/Printing_Poster.jpg)

      This character comes from the Chinese novel 'Shui Hu Zhuan' and is one of my favorites.
      Complete end-to-end production: modeling, rendering, 3D printing, and hand-painting.

      ![](images/Printing.jpg)
  - title: Experience
    layout: list
    content:
      - layout: left
        title: MIHOYO
        sub_title: Animator
        caption: 2025.4 — 2025.11
        link: https://www.mihoyo.com/
        quote: >
          miHoYo opened its doors in 2012 and has delivered globally recognized IPs such as Genshin Impact®, Honkai Impact 3rd®, Honkai: Star Rail®, and Zenless Zone Zero®.
        description: |
          3D Character facial expression production.

          ![](images/PlaceHolder.jpg)

      - layout: left
        title: UBISOFT SHANGHAI
        sub_title: Junior Rigger
        caption: 2023.8 — 2025.4
        link: https://www.ubisoft.com/en-us/company/careers/locations/shanghai
        quote: >
          Ubisoft Shanghai studio opened its door in 1996 and has worked on major Ubisoft brands such as Just Dance®, Far Cry®, The Crew®, Assassin’s Creed®, Might & Magic® and Tom Clancy’s Splinter Cell®.
        description: |
          Animal rigging,
          Animation system implementation in-engine.

          ![](images/UBI_1.gif)

          Character, costume, and gear rigging.

          ![](images/UBI_2.gif)

          Pipeline tools coding.
      - layout: left
        title: HYPERGRYPH
        sub_title: Intern CFX
        caption: 2022.6 —​ 2022.12
        link: https://www.hypergryph.com/
        quote: >
          Hypergryph was founded in 2017 and has become a leading creative force in the Chinese game industry, known for developing major titles such as Arknights®, Ex Astris®, and POPUCOM®.
        description: |
          Hair and cloth simulation.

          ![](images/YJ.gif)
  - title: Education
    layout: list
    content:
      - layout: left
        title: Tongji University
        sub_title: Animation (BA)
        caption: 2019 - 2023
        # quote: >
        #   Short institution or course description (optional)
        description: |
          Completed the Animation program at Tongji University with a GPA of 4.79/5, with coursework spanning acting, 2D and 3D animation, modeling, rendering, compositing, and sound design.
  - title: A Little More About Me
    layout: text
    content: |
      **My interests?**
        – Rock ’n’ roll and bass guitar (RHCP hell yes!!).
        – Games (RPG and shooting).
        – Strength training and anything that gets me outdoors.
        – Sudoku.
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
